onlyBuiltDependencies:
  - "@prisma/client"
  - "@prisma/engines"
  - "@tailwindcss/oxide"
  - bcrypt
  - better-sqlite3
  - core-js
  - esbuild
  - node-base64
  - prisma
  - protobufjs
  - sharp
  - unrs-resolver
