# =============================================================================
# CONFIGURATION DES SOURCES DE DONNÉES GRAFANA
# =============================================================================

apiVersion: 1

datasources:
  # Source principale Prometheus
  - name: Prometheus
    type: prometheus
    access: proxy
    orgId: 1
    url: http://prometheus:9090
    basicAuth: false
    isDefault: true
    version: 1
    editable: true
    jsonData:
      httpMethod: POST
      manageAlerts: true
      prometheusType: Prometheus
      prometheusVersion: 2.45.0
      cacheLevel: 'High'
      disableRecordingRules: false
      incrementalQueryOverlapWindow: 10m

  # Base de données PostgreSQL pour requêtes SQL directes
  - name: PostgreSQL
    type: postgres
    access: proxy
    orgId: 1
    url: postgres:5432
    database: ecodeli
    user: monitoring
    secureJsonData:
      password: changeme_monitoring_password
    jsonData:
      sslmode: disable
      maxOpenConns: 10
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 1600
      timescaledb: false

  # Loki pour les logs (optionnel)
  - name: Loki
    type: loki
    access: proxy
    orgId: 1
    url: http://loki:3100
    basicAuth: false
    isDefault: false
    version: 1
    editable: true
    jsonData:
      maxLines: 1000
      derivedFields:
        - datasourceUid: prometheus_uid
          matcherRegex: "trace_id=(\\w+)"
          name: TraceID
          url: "/explore?orgId=1&left=%5B%22now-1h%22,%22now%22,%22Jaeger%22,%7B%22query%22:%22$${__value.raw}%22%7D%5D"

  # Source de données Test (pour développement)
  - name: TestData
    type: testdata
    access: proxy
    orgId: 1
    isDefault: false
    version: 1
    editable: true
    jsonData:
      name: TestData