# k8s/base/services/web-service.yaml
apiVersion: v1
kind: Service
metadata:
  name: ecodeli-web-service
  namespace: ecodeli
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app: ecodeli-web