// Routes EcoDeli - Référence complète

export const ROUTES = {
  // Auth
  auth: {
    login: '/login',
    register: '/register',
    registerClient: '/register/client',
    registerDeliverer: '/register/deliverer',
    registerMerchant: '/register/merchant',
    registerProvider: '/register/provider',
    forgotPassword: '/forgot-password',
    resetPassword: '/reset-password',
    verifyEmail: '/verify-email',
    twoFactorSetup: '/two-factor/setup',
    twoFactorVerify: '/two-factor/verify',
    accountInactive: '/account-inactive',
    accountSuspended: '/account-suspended',
    sessionExpired: '/session-expired',
  },

  // Public
  public: {
    home: '/',
    about: '/about',
    services: '/services',
    pricing: '/pricing',
    blog: '/blog',
    blogPost: (slug: string) => /blog/,
    contact: '/contact',
    faq: '/faq',
    shipping: '/shipping',
    becomeDelivery: '/become-delivery',
    partners: '/partners',
    partnersMerchants: '/partners/merchants',
    partnersProviders: '/partners/providers',
    legal: '/legal',
    cgu: '/legal/cgu',
    cgv: '/legal/cgv',
    privacy: '/privacy',
    terms: '/terms',
  },

  // Admin
  admin: {
    dashboard: '/admin',
    announcements: '/admin/announcements',
    audit: '/admin/audit',
    billing: '/admin/billing',
    clients: '/admin/clients',
    clientDetail: (id: string) => /admin/clients/,
    config: '/admin/config',
    contracts: '/admin/contracts',
    deliverers: '/admin/deliverers',
    deliveries: '/admin/deliveries',
    finance: '/admin/finance',
    invoices: '/admin/invoices',
    logs: '/admin/logs',
    merchants: '/admin/merchants',
    payments: '/admin/payments',
    prestations: '/admin/prestations',
    providers: '/admin/providers',
    reports: '/admin/reports',
    services: '/admin/services',
    settings: '/admin/settings',
    support: '/admin/support',
    users: '/admin/users',
    verifications: '/admin/verifications',
    warehouses: '/admin/warehouses',
  },

  // Client
  client: {
    dashboard: '/client',
    announcements: '/client/announcements',
    appointments: '/client/appointments',
    contracts: '/client/contracts',
    deliveries: '/client/deliveries',
    invoices: '/client/invoices',
    messages: '/client/messages',
    notifications: '/client/notifications',
    payments: '/client/payments',
    profile: '/client/profile',
    reviews: '/client/reviews',
    services: '/client/services',
    storage: '/client/storage',
    subscription: '/client/subscription',
  },

  // Deliverer
  deliverer: {
    dashboard: '/deliverer',
    announcements: '/deliverer/announcements',
    availability: '/deliverer/availability',
    contracts: '/deliverer/contracts',
    deliveries: '/deliverer/deliveries',
    documents: '/deliverer/documents',
    messages: '/deliverer/messages',
    myRoutes: '/deliverer/my-routes',
    notifications: '/deliverer/notifications',
    payments: '/deliverer/payments',
    profile: '/deliverer/profile',
    schedule: '/deliverer/schedule',
    stats: '/deliverer/stats',
    wallet: '/deliverer/wallet',
  },

  // Merchant
  merchant: {
    dashboard: '/merchant',
    announcements: '/merchant/announcements',
    catalog: '/merchant/catalog',
    contract: '/merchant/contract',
    deliveries: '/merchant/deliveries',
    documents: '/merchant/documents',
    invoices: '/merchant/invoices',
    messages: '/merchant/messages',
    orders: '/merchant/orders',
    payments: '/merchant/payments',
    profile: '/merchant/profile',
    stats: '/merchant/stats',
    verification: '/merchant/verification',
  },

  // Provider
  provider: {
    dashboard: '/provider',
    appointments: '/provider/appointments',
    billing: '/provider/billing',
    contracts: '/provider/contracts',
    documents: '/provider/documents',
    invoices: '/provider/invoices',
    messages: '/provider/messages',
    profile: '/provider/profile',
    ratings: '/provider/ratings',
    schedule: '/provider/schedule',
    services: '/provider/services',
    skills: '/provider/skills',
    stats: '/provider/stats',
    verification: '/provider/verification',
  },

  // Common
  common: {
    help: '/common/help',
    helpArticle: (topic: string) => /common/help/,
    settings: '/common/settings',
    settingsLanguage: '/common/settings/language',
    settingsNotifications: '/common/settings/notifications',
    settingsSecurity: '/common/settings/security',
  },
} as const;