version: "3.8"
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    # Optionnel : monter le répertoire pour le développement
    volumes:
      - .:/app
    command: npm start
