<<<<<<< Updated upstream
=======
version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    restart: always
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/ecodeli?schema=public
      - NEXTAUTH_URL=https://ecodeli.com
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
    depends_on:
      - db
    networks:
      - ecodeli
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G

  db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=ecodeli
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - ecodeli
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 1G

  nginx:
    image: nginx:alpine
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/ssl:/etc/nginx/ssl
      - ../public:/var/www/public
    depends_on:
      - app
    networks:
      - ecodeli

volumes:
  postgres_data:

networks:
  ecodeli:
    driver: bridge 
>>>>>>> Stashed changes
