// Enums pour la gestion des utilisateurs
export enum UserRole {
  CLIENT = 'CLIENT',
  DELIVERER = 'DELIVERER',
  MERCHANT = 'MERCHANT',
  PROVIDER = 'PROVIDER',
  ADMIN = 'ADMIN',
}

export enum UserStatus {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  SUSPENDED = 'SUSPENDED',
  PENDING_VERIFICATION = 'PENDING_VERIFICATION',
}

// Enum pour la gestion des vérifications
export enum VerificationStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

// Enums pour la gestion des documents
export enum DocumentStatus {
  PENDING = 'PENDING',
  APPROVED = 'APPROVED',
  REJECTED = 'REJECTED',
}

export enum DocumentType {
  ID_CARD = 'ID_CARD',
  DRIVING_LICENSE = 'DRIVING_LICENSE',
  VEHICLE_REGISTRATION = 'VEHICLE_REGISTRATION',
  INSURANCE = 'INSURANCE',
<<<<<<< HEAD
  CRIMINAL_RECORD = 'CRIMINAL_RECORD',
  PROFESSIONAL_CERTIFICATION = 'PROFESSIONAL_CERTIFICATION',
=======
  QUALIFICATION_CERTIFICATE = 'QUALIFICATION_CERTIFICATE',
  PROOF_OF_ADDRESS = 'PROOF_OF_ADDRESS',
  BUSINESS_REGISTRATION = 'BUSINESS_REGISTRATION',
>>>>>>> 1b63c146c3df5c00cc1ce2e81d59f8f5633cf417
  SELFIE = 'SELFIE',
  OTHER = 'OTHER',
}

// Types de tokens
export enum TokenType {
  EMAIL_VERIFICATION = 'EMAIL_VERIFICATION',
  PASSWORD_RESET = 'PASSWORD_RESET',
  TWO_FACTOR_AUTH = 'TWO_FACTOR_AUTH',
}
