# Configuration Prometheus pour EcoDeli
global:
  scrape_interval: 15s
  evaluation_interval: 15s

# Règles d'alerting
rule_files:
  - "rules/*.yml"

# Configuration des cibles à surveiller
scrape_configs:
  # Prometheus lui-même
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']

  # Application Web Next.js
  - job_name: 'ecodeli-web'
    static_configs:
      - targets: ['web:3000']
    metrics_path: '/api/metrics'
    scrape_interval: 30s

  # Application Desktop Java
  - job_name: 'ecodeli-desktop'
    static_configs:
      - targets: ['desktop:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 30s

  # PostgreSQL via l'exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  # Redis via l'exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Node Exporter pour les métriques système
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s

  # Nginx (si configuré avec metrics)
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:80']
    metrics_path: '/nginx_status'
    scrape_interval: 30s

# Configuration des alertes
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093 