# =============================================================================
# RÈGLES D'ALERTE PROMETHEUS POUR ECODELI
# =============================================================================

groups:
  # Alertes sur l'infrastructure système
  - name: infrastructure
    rules:
      # Serveur en panne
      - alert: InstanceDown
        expr: up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Instance {{ $labels.instance }} est en panne"
          description: "L'instance {{ $labels.instance }} du job {{ $labels.job }} est en panne depuis plus d'1 minute."

      # Utilisation élevée du CPU
      - alert: HighCpuUsage
        expr: 100 - (avg(rate(node_cpu_seconds_total{mode="idle"}[5m])) * 100) > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Utilisation CPU élevée"
          description: "L'utilisation CPU est à {{ $value }}% depuis plus de 5 minutes."

      # Utilisation élevée de la mémoire
      - alert: HighMemoryUsage
        expr: (1 - (node_memory_MemAvailable_bytes / node_memory_MemTotal_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Utilisation mémoire élevée"
          description: "L'utilisation mémoire est à {{ $value }}% depuis plus de 5 minutes."

      # Espace disque faible
      - alert: LowDiskSpace
        expr: (1 - (node_filesystem_avail_bytes / node_filesystem_size_bytes)) * 100 > 85
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Espace disque faible"
          description: "L'espace disque sur {{ $labels.mountpoint }} est utilisé à {{ $value }}%."

  # Alertes sur l'application web
  - name: ecodeli-web
    rules:
      # Taux d'erreur HTTP élevé
      - alert: HighHttpErrorRate
        expr: rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m]) > 0.05
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "Taux d'erreur HTTP élevé"
          description: "Le taux d'erreur HTTP 5xx est de {{ $value | humanizePercentage }} depuis plus de 3 minutes."

      # Temps de réponse élevé
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m])) > 2
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Temps de réponse élevé"
          description: "Le 95e percentile du temps de réponse est de {{ $value }}s depuis plus de 5 minutes."

      # Nombre de connexions actives élevé
      - alert: HighActiveConnections
        expr: nodejs_active_connections > 1000
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Nombre de connexions actives élevé"
          description: "L'application web a {{ $value }} connexions actives."

  # Alertes sur la base de données
  - name: postgresql
    rules:
      # Connexions DB élevées
      - alert: HighDatabaseConnections
        expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Nombre de connexions DB élevé"
          description: "Le nombre de connexions PostgreSQL est à {{ $value }}% de la limite."

      # Temps de requête élevé
      - alert: SlowDatabaseQueries
        expr: pg_stat_activity_max_tx_duration > 300
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Requêtes lentes détectées"
          description: "Des requêtes PostgreSQL durent plus de 5 minutes."

      # Taille de base de données
      - alert: DatabaseSizeGrowth
        expr: increase(pg_database_size_bytes[24h]) > 1073741824  # 1GB par jour
        for: 1h
        labels:
          severity: info
        annotations:
          summary: "Croissance rapide de la base de données"
          description: "La base de données a grandi de {{ $value | humanizeBytes }} en 24h."

  # Alertes sur Redis
  - name: redis
    rules:
      # Utilisation mémoire Redis élevée
      - alert: HighRedisMemoryUsage
        expr: redis_memory_used_bytes / redis_memory_max_bytes * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "Utilisation mémoire Redis élevée"
          description: "Redis utilise {{ $value }}% de sa mémoire allouée."

      # Redis non disponible
      - alert: RedisDown
        expr: redis_up == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "Redis est en panne"
          description: "Le serveur Redis n'est pas accessible."

  # Alertes métier spécifiques à EcoDeli
  - name: ecodeli-business
    rules:
      # Échec de livraisons élevé
      - alert: HighDeliveryFailureRate
        expr: rate(ecodeli_deliveries_failed_total[5m]) / rate(ecodeli_deliveries_total[5m]) > 0.1
        for: 10m
        labels:
          severity: warning
        annotations:
          summary: "Taux d'échec de livraisons élevé"
          description: "Le taux d'échec des livraisons est de {{ $value | humanizePercentage }} depuis 10 minutes."

      # Temps d'attente des livreurs
      - alert: LongDelivererWaitTime
        expr: ecodeli_deliverer_avg_wait_time_seconds > 1800  # 30 minutes
        for: 15m
        labels:
          severity: warning
        annotations:
          summary: "Temps d'attente des livreurs élevé"
          description: "Le temps d'attente moyen des livreurs est de {{ $value }}s."

      # Nombre d'utilisateurs actifs faible
      - alert: LowActiveUsers
        expr: ecodeli_active_users_total < 100
        for: 30m
        labels:
          severity: info
        annotations:
          summary: "Nombre d'utilisateurs actifs faible"
          description: "Seulement {{ $value }} utilisateurs actifs détectés."

      # Problème de paiement
      - alert: HighPaymentFailureRate
        expr: rate(ecodeli_payments_failed_total[5m]) / rate(ecodeli_payments_total[5m]) > 0.05
        for: 5m
        labels:
          severity: critical
        annotations:
          summary: "Taux d'échec de paiements élevé"
          description: "Le taux d'échec des paiements est de {{ $value | humanizePercentage }}."

  # Alertes sur le monitoring lui-même
  - name: monitoring
    rules:
      # Prometheus ne peut pas scraper une cible
      - alert: PrometheusTargetMissing
        expr: up == 0
        for: 2m
        labels:
          severity: warning
        annotations:
          summary: "Cible Prometheus manquante"
          description: "Prometheus ne peut pas scraper {{ $labels.job }}/{{ $labels.instance }}."

      # Configuration Prometheus rechargée
      - alert: PrometheusConfigurationReloaded
        expr: prometheus_config_last_reload_successful == 0
        for: 1m
        labels:
          severity: warning
        annotations:
          summary: "Échec du rechargement de configuration Prometheus"
          description: "Le rechargement de la configuration Prometheus a échoué."